FROM python:3.11-slim

WORKDIR /app


RUN apt-get update && apt-get install -y \
    curl \
    gcc \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock README.md ./

RUN uv sync --frozen

COPY src ./src
COPY scripts ./scripts
COPY data ./data

ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1

CMD ["sh", "-c", "set -euo pipefail; \
uv run alembic -c src/api/db/alembic.ini upgrade head && \
if [ ! -f /app/.ingested ]; then \
  uv run python scripts/ingestion/main.py && \
  touch /app/.ingested; \
fi && \
uv run python scripts/create_admin.py && \
exec uv run uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --log-level info"]