services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.prod
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    depends_on:
      - db
      - vector_db
      - qdrant

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"
    depends_on:
      - backend

  qdrant:
    image: qdrant/qdrant
    volumes:
      - qdrant_storage:/qdrant/storage

  vector_db:
    image: ankane/pgvector
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: vector_db
    volumes:
      - vector_db_data:/var/lib/postgresql/data

  db:
    image: postgres:18-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: bot_db
    command: ["postgres", "-p", "5434"]
    ports:
      - "5434:5434"
    volumes:
      - bot_db_data:/var/lib/postgresql/data

volumes:
  bot_db_data:
  vector_db_data:
  qdrant_storage: