"""drop feedback auto approve positive and negative columns

Revision ID: 43c66e70d7b9
Revises: d9e0f1a2b3c4
Create Date: 2026-04-29 20:42:14.844698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43c66e70d7b9'
down_revision: Union[str, Sequence[str], None] = 'd9e0f1a2b3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('golden_examples', 'query_type',
               existing_type=sa.VARCHAR(length=20),
               comment='static or temporal - temporal queries always require tool calls',
               existing_comment='static or temporal — temporal queries always require tool calls',
               existing_nullable=False,
               existing_server_default=sa.text("'static'::character varying"))
    op.alter_column('message_feedback', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='pending, auto_approved, ai_approved, ai_rejected, reviewed, dismissed',
               existing_comment='pending, auto_approved, reviewed, dismissed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('message_feedback', 'ai_validated',
               existing_type=sa.VARCHAR(length=20),
               comment='valid, invalid, or null if not processed',
               existing_nullable=True)
    op.alter_column('message_feedback', 'ai_reason',
               existing_type=sa.TEXT(),
               comment="AI's reason for validation decision",
               existing_nullable=True)
    op.drop_column('settings', 'feedback_auto_approve_negative')
    op.drop_column('settings', 'guardrail_usecase_description')
    op.drop_column('settings', 'feedback_auto_approve_positive')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('feedback_auto_approve_positive', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('settings', sa.Column('guardrail_usecase_description', sa.TEXT(), server_default=sa.text("'Support bot for incident resolution and troubleshooting queries.'::text"), autoincrement=False, nullable=False))
    op.add_column('settings', sa.Column('feedback_auto_approve_negative', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.alter_column('message_feedback', 'ai_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="AI's reason for validation decision",
               existing_nullable=True)
    op.alter_column('message_feedback', 'ai_validated',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='valid, invalid, or null if not processed',
               existing_nullable=True)
    op.alter_column('message_feedback', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='pending, auto_approved, reviewed, dismissed',
               existing_comment='pending, auto_approved, ai_approved, ai_rejected, reviewed, dismissed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('golden_examples', 'query_type',
               existing_type=sa.VARCHAR(length=20),
               comment='static or temporal — temporal queries always require tool calls',
               existing_comment='static or temporal - temporal queries always require tool calls',
               existing_nullable=False,
               existing_server_default=sa.text("'static'::character varying"))
    # ### end Alembic commands ###
