"""add langfuse config columns to settings

Revision ID: 4a41df53be8f
Revises: 964d5b0c1351
Create Date: 2026-03-08 14:21:13.288174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a41df53be8f'
down_revision: Union[str, Sequence[str], None] = '964d5b0c1351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('langfuse_secret_key_encrypted', sa.Text(), nullable=True))
    op.add_column('settings', sa.Column('langfuse_public_key', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('langfuse_base_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'langfuse_base_url')
    op.drop_column('settings', 'langfuse_public_key')
    op.drop_column('settings', 'langfuse_secret_key_encrypted')
    # ### end Alembic commands ###
