"""update settings with langfuse config

Revision ID: 68e99f253c6c
Revises: 8033d3cd18e1
Create Date: 2025-12-08 13:13:22.991052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e99f253c6c'
down_revision: Union[str, Sequence[str], None] = '8033d3cd18e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('langfuse_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'langfuse_enabled')
    # ### end Alembic commands ###
