"""add-message-metrics-and-timestamps

Revision ID: 964d5b0c1351
Revises: adb45cc8c6cb
Create Date: 2026-03-07 22:59:50.112745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '964d5b0c1351'
down_revision: Union[str, Sequence[str], None] = 'adb45cc8c6cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('responded_at', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('time_to_first_token_ms', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('total_response_time_ms', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('model_id', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('provider_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'provider_type')
    op.drop_column('messages', 'model_id')
    op.drop_column('messages', 'total_response_time_ms')
    op.drop_column('messages', 'time_to_first_token_ms')
    op.drop_column('messages', 'responded_at')
    # ### end Alembic commands ###
