"""drop is_system from roles and permission_sets

Revision ID: adb45cc8c6cb
Revises: j0k1l2m3n4o5
Create Date: 2026-03-07 22:29:37.019818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adb45cc8c6cb'
down_revision: Union[str, Sequence[str], None] = 'j0k1l2m3n4o5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('golden_examples', 'source_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='positive, negative, or manual',
               existing_nullable=False)
    op.alter_column('golden_examples', 'approval_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='auto or manual',
               existing_nullable=False,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('golden_examples', 'qdrant_point_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Reference to vector in Qdrant',
               existing_nullable=True)
    op.drop_column('permission_sets', 'is_system')
    op.drop_column('roles', 'is_system')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('is_system', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('permission_sets', sa.Column('is_system', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.alter_column('golden_examples', 'qdrant_point_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Reference to vector in Qdrant',
               existing_nullable=True)
    op.alter_column('golden_examples', 'approval_type',
               existing_type=sa.VARCHAR(length=20),
               comment='auto or manual',
               existing_nullable=False,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('golden_examples', 'source_type',
               existing_type=sa.VARCHAR(length=20),
               comment='positive, negative, or manual',
               existing_nullable=False)
    # ### end Alembic commands ###
